# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

matrix:
  include:
    - os: osx
      r: release
    - os: osx
      disable_homebrew: true
    - os: linux
      r: devel
    - os: linux
      r: release
